services:
  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"

  postgres:
    profiles: ["local-db"]
    image: postgres:18
    container_name: clinix-postgres
    restart: always
    environment:
      POSTGRES_DB: "clinix_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - clinix_postgres_data:/var/lib/postgresql

volumes:
  clinix_postgres_data:
